name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    strategy:
      matrix:
        node-version: [8.x, 10.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with: 
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm install -g react-native-cli
        cd ios && pod install && cd ..
        react-native run ios
        npm test
      env:
        CI: true
